spring:
  profiles:
    active: database

---
spring:
  datasource:
    url: jdbc:mysql://localhost/voucher_management
    username: root
    password: root1234!
    driver-class-name: com.mysql.cj.jdbc.Driver
